name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './250815_airk/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./250815_airk
      
      - name: Build Slidev
        run: npm run build -- --base /public-slides/250815_airk/
        working-directory: ./250815_airk
      
      - name: Create deployment directory
        run: |
          mkdir -p ./deploy
          cp index.html ./deploy/
          mkdir -p ./deploy/250815_airk
          cp -r ./250815_airk/dist/* ./deploy/250815_airk/
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deploy'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4